### ISSUE TITLE
Missing attributes on Sublime 3.0

### ISSUE THREAD

**Issue by tg** [golang/sublime-build#31]
I've upgraded Sublime Text 3 from the last beta to the latest (and first) stable version (3.0 build 3143), which seemed to break Golang Build package. Now, after running build, the following error pops up in the console:

```
Traceback (most recent call last):
  File "golang_build in /Users/tg/Library/Application Support/Sublime Text 3/Installed Packages/Golang Build.sublime-package", line 508, in _get_config
AttributeError: 'module' object has no attribute 'subprocess_info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 797, in run_
    return self.run()
  File "golang_build in /Users/tg/Library/Application Support/Sublime Text 3/Installed Packages/Golang Build.sublime-package", line 92, in run
  File "golang_build in /Users/tg/Library/Application Support/Sublime Text 3/Installed Packages/Golang Build.sublime-package", line 516, in _get_config
AttributeError: 'module' object has no attribute 'ExecutableError'
```

I'm on macOS 10.12.6, go version 1.9.

**Comment by teesudo** [comment]
Have the same issue, anyone can help?

**Comment by hrom512** [comment]
+1
