### ISSUE TITLE
Issues on Windows 8 with Sublime Text 3 

### ISSUE THREAD

**Issue by wheineman** [golang/sublime-build#6]
Tools (go-build) don't work. Here's the stacktrace from the console:

Traceback (most recent call last):
  File "C:\Users\heinemanwp\MyApps\Sublime Text 3\sublime_plugin.py", line 535, in run_
    return self.run()
  File "golang_build in C:\Users\heinemanwp\AppData\Roaming\Sublime Text 3\Installed Packages\Golang Build.sublime-package", line 88, in run
  File "golang_build in C:\Users\heinemanwp\AppData\Roaming\Sublime Text 3\Installed Packages\Golang Build.sublime-package", line 466, in _get_config
  File "C:\Users\HEINEM~1\AppData\Roaming\SUBLIM~1\Packages\GOLANG~1\all\golangconfig.py", line 130, in subprocess_info
    path, _ = executable_path(executable_name, view=view, window=window)
  File "C:\Users\HEINEM~1\AppData\Roaming\SUBLIM~1\Packages\GOLANG~1\all\golangconfig.py", line 362, in executable_path
    setting, source = _get_most_specific_setting('PATH', view, window)
  File "C:\Users\HEINEM~1\AppData\Roaming\SUBLIM~1\Packages\GOLANG~1\all\golangconfig.py", line 469, in _get_most_specific_setting
    window_settings = window.project_data().get('settings', {}).get('golang', {})
AttributeError: 'NoneType' object has no attribute 'get'

My golang.sublime-settings file:

{
    "PATH": "D:\go\bin",
    "GOPATH": "D:\msys64\home\HeinemanWP\go"
}

**Comment by wbond** [comment]
Perfect, thanks for the bug report!

**Comment by wbond** [comment]
This was fixed by version 0.8.1 of https://github.com/golang/sublime-config, and should no longer be an issue if you are on version 0.8.3 or newer of Golang Build.

**Comment by wbond** [comment]
@jbuberel Can you close this?
